name: release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [published]
    
env:
  CGO_ENABLED: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Build unoserver-rest-api
        run: |
          make
          make build VERSION=${{ github.event.release.tag_name }}
          cd bin ; for f in unoserver-rest-api* ; do sha256sum "$f" > "$f".sha256 ; done

      - name: Build s6-overlay-module
        run: |
          make s6-overlay-module
          cd output ; for f in *.tar* ; do sha256sum "$f" > "$f".sha256 ; done

      - name: Upload releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/*
            output/s6-overlay-*
